services:
  mysql_5.7.16:
    image: mysql:5.7.16
    container_name: mysql_5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mysql_5.7.16:/var/lib/mysql
    restart: unless-stopped